version: "3.9"
services:
  app-reporting-tool:
    container_name: reporting-tool
    image: reporting-tool
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ORIGIN=http://localhost:3000
    ports:
      - "3000:3000"
